'use client';

import { usePathname } from 'next/navigation';
import { Activity, AlertTriangle, BarChart3, Bell, CircleDollarSign, Database, Globe2, LockKeyhole, Monitor, Settings, ShieldCheck, Users, WalletCards } from 'lucide-react';

const items=['DASHBOARD','PRIVATE USERS','ALLOWLIST','SANDBOX','TRADING MONITOR','DERIV','MT5','WALLETS','LEDGER','PROFIT UNITS','PAYOUTS','LOCAL TRANSACTIONS','AI PERFORMANCE','ANNOUNCEMENTS','EVENTS','VIDEOS','SECURITY','INCIDENTS','SYSTEM HEALTH'];
const iconMap:any={DASHBOARD:BarChart3,'PRIVATE USERS':Users,ALLOWLIST:ShieldCheck,SANDBOX:WalletCards,'TRADING MONITOR':Activity,DERIV:Globe2,MT5:Globe2,WALLETS:WalletCards,LEDGER:Database,'PROFIT UNITS':CircleDollarSign,PAYOUTS:CircleDollarSign,'LOCAL TRANSACTIONS':CircleDollarSign,'AI PERFORMANCE':BarChart3,ANNOUNCEMENTS:Bell,EVENTS:Bell,VIDEOS:Monitor,SECURITY:ShieldCheck,INCIDENTS:AlertTriangle,'SYSTEM HEALTH':Settings};
export default function Admin(){const path=usePathname();const active=path.split('/').filter(Boolean)[1]||'dashboard';return <div className="adminShell"><aside><div className="brand"><span>O</span><b>ORENZA</b></div><div className="privateTag"><LockKeyhole size={14}/> ADMIN CONTROL</div><nav>{items.map(x=>{const key=x.toLowerCase().replaceAll(' ','-');const Icon=iconMap[x]||Settings;return <a className={active===key?'active':''} href={`/admin/${key}`} key={x}><Icon size={15}/><span>{x}</span></a>})}</nav><div className="sideSecurity"><ShieldCheck size={18}/><div><b>Admin security</b><small>Secrets are never displayed</small></div></div></aside><main><div className="topbar"><span>ADMIN / {items.find(x=>x.toLowerCase().replaceAll(' ','-')===active)||'DASHBOARD'}</span><div><span className="badge danger">PRIVILEGED</span><span className="badge good">SECURE MODE</span></div></div><div className="content"><AdminContent active={active}/></div></main></div>}
function AdminContent({active}:{active:string}){if(active!=='dashboard')return <><header className="pageHead"><div><p className="eyebrow">ADMIN CONTROL</p><h1>{active.replaceAll('-',' ')}</h1><p className="muted">Controlled administrative workspace. Every sensitive action requires authorization and audit logging.</p></div></header><div className="warning"><AlertTriangle size={18}/><span>No raw credentials or uncontrolled balance editing is exposed. Backend enforcement is required before operational actions are enabled.</span></div><div className="signalGrid">{['Records','Status','Audit log'].map(x=><div className="card" key={x}><span className="label">{x.toUpperCase()}</span><strong className="metricValue">Awaiting data</strong><small>Server-controlled</small></div>)}</div></>;return <><header className="pageHead"><div><p className="eyebrow">PRIVILEGED OPERATIONS</p><h1>Admin Dashboard</h1><p className="muted">Monitor private access, provider connections, sandbox allocation, payout requests and system health.</p></div></header><div className="metricGrid">{[['PRIVATE USERS','—',Users],['CONNECTED DERIV','—',Globe2],['CONNECTED MT5','—',Globe2],['SANDBOX ALLOCATION','—',WalletCards],['OPEN ACTIVITIES','—',Activity],['PAYOUT REQUESTS','—',CircleDollarSign],['SECURITY ALERTS','—',AlertTriangle],['SYSTEM HEALTH','—',ShieldCheck]].map(([a,b,I])=><div className="card" key={a as string}><div className="metricIcon"><I size={18}/></div><span className="label">{a as string}</span><strong className="metricValue">{b as string}</strong><small>Live admin data required</small></div>)}</div><section className="section"><div className="sectionHead"><div><h2>Security rule</h2><p>Administrative actions are auditable and never expose secrets.</p></div></div><div className="warning"><ShieldCheck size={18}/><span>Credential status is limited to CONFIGURED, ACTIVE, EXPIRING, ROTATION REQUIRED or DISABLED.</span></div></section></>}
