'use client';

import { usePathname } from 'next/navigation';
import { Activity, AlertTriangle, BarChart3, Bell, CircleDollarSign, Database, Globe2, KeyRound, LockKeyhole, Monitor, Settings, ShieldCheck, UserCheck, Users, WalletCards, Bot, ClipboardCheck } from 'lucide-react';

const items=['DASHBOARD','USERS','ALLOWLIST','KYC & AML','SANDBOX FUNDING','TRADING MONITOR','DERIV','MT5','WALLETS','LEDGER','PROFIT UNITS','PAYOUT APPROVALS','LOCAL TRANSACTIONS','AI ACTION QUEUE','RISK & FRAUD','NOTIFICATIONS','CONTENT','SECURITY','INCIDENTS','SYSTEM HEALTH','RUNTIME CONTROLS','AUDIT LOG'];
const iconMap:Record<string,any>={DASHBOARD:BarChart3,USERS:Users,ALLOWLIST:ShieldCheck,'KYC & AML':UserCheck,'SANDBOX FUNDING':WalletCards,'TRADING MONITOR':Activity,DERIV:Globe2,MT5:KeyRound,WALLETS:WalletCards,LEDGER:Database,'PROFIT UNITS':CircleDollarSign,'PAYOUT APPROVALS':ClipboardCheck,'LOCAL TRANSACTIONS':CircleDollarSign,'AI ACTION QUEUE':Bot,'RISK & FRAUD':AlertTriangle,NOTIFICATIONS:Bell,CONTENT:Monitor,SECURITY:ShieldCheck,INCIDENTS:AlertTriangle,'SYSTEM HEALTH':Settings,'RUNTIME CONTROLS':Settings,'AUDIT LOG':ClipboardCheck};

export default function Admin(){const path=usePathname();const active=path.split('/').filter(Boolean)[1]||'dashboard';return <div className="adminShell"><aside><div className="brand"><span>O</span><b>ORENZA</b></div><div className="privateTag"><LockKeyhole size={14}/> OWNER ADMIN</div><nav>{items.map(x=>{const key=x.toLowerCase().replaceAll(' ','-').replaceAll('&','and');const Icon=iconMap[x]||Settings;return <a className={active===key?'active':''} href={`/admin/${key}`} key={x}><Icon size={15}/><span>{x}</span></a>})}</nav><div className="sideSecurity"><ShieldCheck size={18}/><div><b>Owner security</b><small>No provider secrets displayed</small></div></div></aside><main><div className="topbar"><span>ORENZA ADMIN / {items.find(x=>x.toLowerCase().replaceAll(' ','-').replaceAll('&','and')===active)||'DASHBOARD'}</span><div><span className="badge danger">PRIVILEGED</span><span className="badge good">OWNER CONTROL</span></div></div><div className="content"><AdminContent active={active}/></div></main></div>}

function AdminContent({active}:{active:string}){if(active!=='dashboard')return <><header className="pageHead"><div><p className="eyebrow">OWNER ADMIN CONTROL</p><h1>{active.replaceAll('-',' ')}</h1><p className="muted">Backend-controlled administrative workspace. Sensitive actions are policy-gated, audited and approval-aware.</p></div></header><div className="warning"><AlertTriangle size={18}/><span>AI can recommend and perform policy-permitted operations. Real-money payouts and other critical actions require explicit owner approval.</span></div><div className="signalGrid">{['Backend records','Pending approvals','AI actions','Audit trail'].map(x=><div className="card" key={x}><span className="label">{x.toUpperCase()}</span><strong className="metricValue">Live backend</strong><small>Server-controlled</small></div>)}</div></>;return <><header className="pageHead"><div><p className="eyebrow">ORENZA OWNER CONTROL CENTER</p><h1>Admin Dashboard</h1><p className="muted">Control users, KYC, funding, Deriv/MT5 connections, AI actions, risk, ledger, payouts and system health from a dedicated privileged workspace.</p></div></header><div className="metricGrid">{[['USERS','Backend',Users],['KYC & AML','Backend',UserCheck],['DERIV','Live feed',Globe2],['MT5','Server',KeyRound],['SANDBOX','Policy',WalletCards],['PENDING APPROVALS','Queue',ClipboardCheck],['AI ACTIONS','Queue',Bot],['SECURITY','Monitored',ShieldCheck]].map(([a,b,I])=><div className="card" key={a as string}><div className="metricIcon"><I size={18}/></div><span className="label">{a as string}</span><strong className="metricValue">{b as string}</strong><small>Canonical backend source</small></div>)}</div><section className="section"><div className="sectionHead"><div><h2>Owner approval rule</h2><p>AI-generated critical actions stop here until you approve or decline them.</p></div></div><div className="warning"><ShieldCheck size={18}/><span>Real-money payout execution, critical KYC exceptions, security overrides and live runtime changes remain owner-authorized.</span></div></section></>}
