'use client';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {CheckCircle2,ShieldCheck,Camera,Mail,RefreshCw} from 'lucide-react';
import {getSupabaseBrowser} from '../../lib/supabase-browser';

export default function KycPage(){
 const router=useRouter(); const[status,setStatus]=useState('NOT_STARTED'); const[caseId,setCaseId]=useState(''); const[msg,setMsg]=useState(''); const[busy,setBusy]=useState(false); const[step,setStep]=useState<'case'|'otp'|'face'>('case'); const[challenge,setChallenge]=useState(''); const[email,setEmail]=useState(''); const[code,setCode]=useState(''); const[verified,setVerified]=useState(false); const[stream,setStream]=useState<MediaStream|null>(null); const videoRef=useRef<HTMLVideoElement>(null);
 useEffect(()=>{(async()=>{const s=getSupabaseBrowser();const{data:{user}}=await s.auth.getUser();if(!user){router.replace('/login');return}setEmail(user.email||'');const{data}=await s.rpc('get_drive_invest_kyc_status');if(data?.[0]){setCaseId(data[0].case_id);setStatus(data[0].status)}})();return()=>{stream?.getTracks().forEach(t=>t.stop())}},[router]);
 async function start(){setBusy(true);setMsg('');const s=getSupabaseBrowser();const{data,error}=await s.rpc('start_drive_invest_kyc',{p_verification_level:'STANDARD'});if(error)setMsg(error.message);else{setCaseId(data.id);setStatus(data.status);setMsg('KYC case created. Send the one-time email code to continue.')}setBusy(false)}
 async function sendCode(){setBusy(true);setMsg('');try{const s=getSupabaseBrowser();const{data:{session}}=await s.auth.getSession();if(!session)throw new Error('Session expired. Sign in again.');const r=await fetch('/api/kyc/verification-code',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to send code');setChallenge(d.challenge_id);setEmail(d.email||email);setCode('');setStep('otp');setMsg('A one-time code was sent to your verified email address.')}catch(e){setMsg(e instanceof Error?e.message:'Unable to send code')}setBusy(false)}
 async function verifyCode(){setBusy(true);setMsg('');try{const s=getSupabaseBrowser();const{data:{session}}=await s.auth.getSession();if(!session)throw new Error('Session expired. Sign in again.');const r=await fetch('/api/kyc/verification-code/verify',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({challenge_id:challenge,code})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Incorrect code');setVerified(true);setStep('face');setMsg('Email verified. Camera verification is next.')}catch(e){setMsg(e instanceof Error?e.message:'Unable to verify code')}setBusy(false)}
 async function startCamera(){setMsg('');try{const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});setStream(media);if(videoRef.current){videoRef.current.srcObject=media;await videoRef.current.play()}}catch(e){setMsg('Camera permission is required for face evidence. Please allow camera access and try again.')}}
 function stopCamera(){stream?.getTracks().forEach(t=>t.stop());setStream(null)}
 return <main style={{minHeight:'100vh',background:'#FAF9F6',padding:30,color:'#0B192B'}}><div style={{maxWidth:760,margin:'auto'}}><p className="eyebrow">ORENZA · KYC</p><h1 style={{color:'#2A402D'}}>Identity verification</h1><p className="muted">Secure, step-by-step verification. The server generates a single-use code, sends it to your verified email, then unlocks the camera evidence step. Final KYC approval remains a human decision.</p>
 <section className="card" style={{marginTop:18}}><div style={{display:'flex',justifyContent:'space-between'}}><strong>Status: {status}</strong><ShieldCheck size={19}/></div>
 {!caseId&&<button className="btn" onClick={start} disabled={busy} style={{marginTop:16}}>Start KYC</button>}
 {caseId&&step==='case'&&<div style={{marginTop:16}}><div className="notice"><CheckCircle2 size={18}/><div><strong>KYC case opened</strong><span>Next: confirm ownership of the verified email with a one-time code.</span></div></div><button className="btn" onClick={sendCode} disabled={busy} style={{marginTop:16}}><Mail size={17}/> {busy?'Sending…':'Send verification code'}</button></div>}
 {caseId&&step==='otp'&&<div style={{marginTop:16}}><div className="notice"><Mail size={18}/><div><strong>Check your email</strong><span>Code sent to {email.replace(/^(.{2}).*(@.*)$/,'$1••••$2')}. It expires in 10 minutes and can only be used once.</span></div></div><label style={{display:'block',marginTop:18,fontWeight:700}}>6-digit verification code<input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} style={{display:'block',width:'100%',fontSize:26,letterSpacing:8,padding:12,marginTop:7}}/></label><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:12}}><button className="btn" onClick={verifyCode} disabled={busy||code.length!==6}>{busy?'Checking…':'Verify code'}</button><button className="btn secondary" onClick={sendCode} disabled={busy}><RefreshCw size={16}/> Resend</button></div></div>}
 {caseId&&step==='face'&&<div style={{marginTop:16}}><div className="notice"><CheckCircle2 size={18}/><div><strong>Email verified</strong><span>Your one-time challenge is consumed. Continue with camera evidence.</span></div></div><div style={{marginTop:18,background:'#111',borderRadius:14,overflow:'hidden',minHeight:280,display:'grid',placeItems:'center'}}>{stream?<video ref={videoRef} muted playsInline style={{width:'100%',maxHeight:440,objectFit:'cover'}}/>:<div style={{color:'#fff',textAlign:'center',padding:28}}><Camera size={42}/><p>Camera preview will appear here.</p></div>}</div><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:12}}>{!stream?<button className="btn" onClick={startCamera}><Camera size={17}/> Start face camera</button>:<button className="btn secondary" onClick={stopCamera}>Stop camera</button>}</div><p className="muted" style={{marginTop:12}}>This camera step captures identity evidence. It does not claim biometric matching or automatic KYC approval unless a dedicated identity provider is configured.</p></div>}
 {msg&&<p className="muted" style={{marginTop:14}}>{msg}</p>}</section><div style={{display:'flex',gap:10,marginTop:14,flexWrap:'wrap'}}><button className="btn secondary" onClick={()=>router.push('/mt5')}>Back to MT5</button><button className="btn secondary" onClick={()=>router.push('/home')}>Main app</button></div></div></main>
}
