'use client';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {CheckCircle2,ShieldCheck,Camera,RotateCcw,FileText} from 'lucide-react';
import {getSupabaseBrowser} from '../../lib/supabase-browser';

export default function KycPage(){
 const router=useRouter();const[status,setStatus]=useState('NOT_STARTED');const[caseId,setCaseId]=useState('');const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);const[step,setStep]=useState<'case'|'id'|'face'|'captured'>('case');const[stream,setStream]=useState<MediaStream|null>(null);const[photo,setPhoto]=useState('');const videoRef=useRef<HTMLVideoElement>(null);const canvasRef=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{(async()=>{const s=getSupabaseBrowser();const{data:{user}}=await s.auth.getUser();if(!user){router.replace('/login');return}const{data}=await s.rpc('get_drive_invest_kyc_status');if(data?.[0]){setCaseId(data[0].case_id);setStatus(data[0].status)}})();return()=>{stream?.getTracks().forEach(t=>t.stop())}},[router,stream]);
 async function start(){setBusy(true);setMsg('');const s=getSupabaseBrowser();const{data,error}=await s.rpc('start_drive_invest_kyc',{p_verification_level:'STANDARD'});if(error)setMsg(error.message);else{setCaseId(data.id);setStatus(data.status);setStep('id');setMsg('KYC case created. Select your government-issued ID and continue.')}setBusy(false)}
 async function startCamera(){setMsg('');try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera access is not supported by this browser.');const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});setStream(media);requestAnimationFrame(async()=>{if(videoRef.current){videoRef.current.srcObject=media;await videoRef.current.play()}})}catch(e){setMsg(e instanceof Error?e.message:'Camera permission is required. Please allow camera access and try again.')}}
 function stopCamera(){stream?.getTracks().forEach(t=>t.stop());setStream(null)}
 function capture(){const video=videoRef.current,canvas=canvasRef.current;if(!video||!canvas||video.videoWidth===0){setMsg('Start the camera and wait for the preview before capturing.');return}canvas.width=video.videoWidth;canvas.height=video.videoHeight;const ctx=canvas.getContext('2d');if(!ctx){setMsg('Unable to capture camera evidence.');return}ctx.drawImage(video,0,0,canvas.width,canvas.height);setPhoto(canvas.toDataURL('image/jpeg',0.9));stopCamera();setStep('captured');setMsg('Face evidence captured on this device. Final KYC approval still requires human review and an approved identity-verification provider.')} 
 function retake(){setPhoto('');setStep('face');setMsg('Retake the camera evidence when ready.')}
 return <main style={{minHeight:'100vh',background:'#FAF9F6',padding:30,color:'#0B192B'}}><div style={{maxWidth:760,margin:'auto'}}><p className="eyebrow">ORENZA · KYC</p><h1 style={{color:'#2A402D'}}>Identity verification</h1><p className="muted">Founder test mode: email OTP is not required for this evidence-collection path. Government ID and face evidence can be reviewed, but this flow never marks KYC approved and does not unlock real-money features.</p>
 <section className="card" style={{marginTop:18}}><div style={{display:'flex',justifyContent:'space-between'}}><strong>Status: {status}</strong><ShieldCheck size={19}/></div>
 {!caseId&&<button className="btn" onClick={start} disabled={busy} style={{marginTop:16}}>{busy?'Starting…':'Start KYC'}</button>}
 {caseId&&step==='id'&&<div style={{marginTop:16}}><div className="notice"><FileText size={18}/><div><strong>Government-issued ID</strong><span>Select the document you intend to use for your normal KYC review. Upload/provider verification is not yet connected in this build.</span></div></div><select defaultValue="" style={{display:'block',width:'100%',padding:12,marginTop:16}}><option value="" disabled>Select document type</option><option>International passport</option><option>National identity card</option><option>Driver's licence</option><option>Voter's card</option></select><button className="btn" onClick={()=>setStep('face')} style={{marginTop:14}}>Continue to face evidence</button></div>}
 {caseId&&step==='face'&&<div style={{marginTop:16}}><div className="notice"><CheckCircle2 size={18}/><div><strong>ID step recorded for review</strong><span>Position your face inside the preview, then capture evidence.</span></div></div><div style={{marginTop:18,background:'#111',borderRadius:14,overflow:'hidden',minHeight:280,display:'grid',placeItems:'center'}}>{stream?<video ref={videoRef} muted playsInline style={{width:'100%',maxHeight:440,objectFit:'cover'}}/>:<div style={{color:'#fff',textAlign:'center',padding:28}}><Camera size={42}/><p>Start your front camera to continue.</p></div>}</div><canvas ref={canvasRef} style={{display:'none'}}/><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:12}}>{!stream?<button className="btn" onClick={startCamera}><Camera size={17}/> Start face camera</button>:<><button className="btn" onClick={capture}><Camera size={17}/> Capture face evidence</button><button className="btn secondary" onClick={stopCamera}>Stop camera</button></>}</div><p className="muted" style={{marginTop:12}}>This is evidence capture only. No biometric match or automatic KYC approval is claimed without a configured identity-verification provider.</p></div>}
 {caseId&&step==='captured'&&<div style={{marginTop:16}}><div className="notice"><CheckCircle2 size={18}/><div><strong>Evidence captured</strong><span>Your face image is held in this browser session for review. It has not been uploaded or used for biometric matching.</span></div></div>{photo&&<img src={photo} alt="Captured face evidence preview" style={{width:'100%',maxHeight:440,objectFit:'cover',borderRadius:14,marginTop:16}}/>}<div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:12}}><button className="btn secondary" onClick={retake}><RotateCcw size={16}/> Retake</button></div><p className="muted" style={{marginTop:12}}>Production KYC approval remains blocked until an approved identity-verification provider is connected and the case receives the required human review.</p></div>}
 {msg&&<p className="muted" style={{marginTop:14}}>{msg}</p>}</section><div style={{display:'flex',gap:10,marginTop:14,flexWrap:'wrap'}}><button className="btn secondary" onClick={()=>router.push('/mt5')}>Back to MT5</button><button className="btn secondary" onClick={()=>router.push('/home')}>Main app</button></div></div></main>
}
