'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import {
  Activity, ArrowRight, BarChart3, Bell, Bot, BriefcaseBusiness, CheckCircle2,
  ChevronRight, CircleDollarSign, Clock3, CreditCard, FileText, Globe2, LockKeyhole,
  LogOut, Menu, PlayCircle, Settings, ShieldCheck, Sparkles, TrendingUp, UserRound,
  WalletCards, X, Zap,
} from 'lucide-react';

const nav = [
  ['home','HOME',BriefcaseBusiness], ['markets','MARKETS',Globe2], ['ai-premium','AI PREMIUM',Sparkles],
  ['trade','TRADE / INVEST',TrendingUp], ['portfolio','PORTFOLIO',BarChart3], ['wallet','WALLET',WalletCards],
  ['payout','PAYOUT',CircleDollarSign], ['activity','ACTIVITY',Activity], ['announcements','ANNOUNCEMENTS',Bell],
  ['events','EVENTS',Clock3], ['videos','VIDEOS',PlayCircle], ['settings','SETTINGS',Settings],
] as const;

const labels: Record<string,string> = {
  home:'HOME', sandbox:'SANDBOX', markets:'MARKETS', 'ai-premium':'AI PREMIUM', trade:'TRADE / INVEST', portfolio:'PORTFOLIO', wallet:'WALLET',
  payout:'PAYOUT', activity:'ACTIVITY / LEDGER', announcements:'ANNOUNCEMENTS', events:'EVENTS', videos:'VIDEOS', settings:'SETTINGS',
  security:'SECURITY CENTER', 'market-detail':'MARKET DETAIL', 'payout-history':'PAYOUT HISTORY', 'profit-units':'PROFIT UNITS',
};

type TradeDraft = { account:string; market:string; direction:'BUY'|'SELL'; amount:string; stopLoss:string; takeProfit:string };
const EMPTY_DRAFT: TradeDraft = { account:'SANDBOX', market:'', direction:'BUY', amount:'', stopLoss:'', takeProfit:'' };
const DRAFT_KEY = 'orenza.trade.draft.v1';
const ACTIVITY_KEY = 'orenza.sandbox.activity.v1';

function Badge({children, tone='neutral'}:{children:React.ReactNode;tone?:'neutral'|'good'|'warn'|'danger'}) { return <span className={`badge ${tone}`}>{children}</span>; }
function Card({children, className='' }:{children:React.ReactNode;className?:string}) { return <div className={`card ${className}`}>{children}</div>; }
function Button({children, href, secondary=false, onClick, disabled=false}:{children:React.ReactNode;href?:string;secondary?:boolean;onClick?:()=>void;disabled?:boolean}) {
  if (href) return <Link href={href} className={`btn ${secondary?'secondary':''} ${disabled?'disabled':''}`} aria-disabled={disabled}>{children}<ArrowRight size={16}/></Link>;
  return <button type="button" onClick={onClick} disabled={disabled} className={`btn ${secondary?'secondary':''}`}>{children}<ArrowRight size={16}/></button>;
}
function ProviderState({name, connected=false}:{name:string;connected?:boolean}) { return <div className="provider"><div className="providerIcon"><Globe2 size={18}/></div><div><strong>{name}</strong><small>{connected?'Connected':'Not connected'}</small></div><Badge tone={connected?'good':'neutral'}>{connected?'CONNECTED':'AVAILABLE'}</Badge></div>; }
function PageHead({eyebrow,title,sub,action}:{eyebrow:string;title:string;sub:string;action?:React.ReactNode}) { return <header className="pageHead"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="muted">{sub}</p></div>{action}</header>; }
function Section({title,sub,children}:{title:string;sub:string;children:React.ReactNode}) { return <section className="section"><div className="sectionHead"><div><h2>{title}</h2><p>{sub}</p></div></div>{children}</section>; }
function Metric({label,value,sub,icon:Icon,tone}:{label:string;value:string;sub:string;icon:any;tone?:'good'|'neutral'}) { return <Card><div className="metricIcon"><Icon size={18}/></div><span className="label">{label}</span><strong className="metricValue">{value}</strong><small className={tone==='good'?'goodText':''}>{sub}</small></Card>; }

function Dashboard() {
  return <><PageHead eyebrow="PRIVATE FINANCIAL PLATFORM" title="Good morning" sub="A clear view of sandbox activity and authorized provider infrastructure." action={<Button href="/markets">Explore markets</Button>} />
    <div className="notice"><ShieldCheck size={20}/><div><strong>Private access is active</strong><span>Provider credentials remain server-side. No live execution is enabled from the interface.</span></div></div>
    <div className="metricGrid"><Metric label="SANDBOX" value="$5,000" sub="30-day welcome capital • virtual" icon={WalletCards}/><Metric label="DERIV" value="Connected" sub="Provider account" icon={Globe2} tone="good"/><Metric label="MT5" value="Not Connected" sub="Optional provider" icon={TrendingUp}/><Metric label="PROFIT UNITS" value="0 Units" sub="Internal records" icon={CircleDollarSign}/></div>
    <Section title="Quick actions" sub="Move through the platform without mixing account sources."><div className="quickGrid">{[['/sandbox','SANDBOX',WalletCards],['/markets','MARKETS',Globe2],['/ai-premium','AI PREMIUM',Sparkles],['/wallet','WALLET',CreditCard]].map(([href,title,Icon])=><Link className="quick" href={href as string} key={title as string}><Icon size={19}/><span>{title}</span><ChevronRight size={16}/></Link>)}</div></Section>
    <Section title="Account sources" sub="Balances and provider records stay separate by design."><div className="providerGrid"><ProviderState name="Sandbox Money" connected/><ProviderState name="Deriv" connected/><ProviderState name="MT5"/></div></Section></>;
}

function Sandbox() { return <><PageHead eyebrow="VIRTUAL ENVIRONMENT" title="Sandbox" sub="Virtual trading capital, kept completely separate from provider accounts." action={<Button href="/markets">Explore markets</Button>}/><div className="heroBalance"><span>Welcome sandbox capital</span><strong>$5,000</strong><small>30-day sandbox allocation • virtual activity only • no cash value</small></div><div className="metricGrid three"><Metric label="AVAILABLE" value="$5,000" sub="Virtual" icon={WalletCards}/><Metric label="RESERVED" value="$0" sub="Virtual" icon={LockKeyhole}/><Metric label="SANDBOX P/L" value="$0" sub="No activity" icon={TrendingUp}/></div><div className="warning"><LockKeyhole size={18}/><div><strong>SANDBOX CAPITAL</strong><span>VIRTUAL — THE WELCOME CAPITAL ITSELF IS NOT WITHDRAWABLE</span></div></div><Section title="Sandbox actions" sub="All actions are recorded as virtual activity."><div className="buttonRow"><Button href="/trade">Open sandbox trade</Button><Button href="/activity" secondary>View activity</Button><Button href="/markets" secondary>Explore markets</Button><Button href="/ai-premium" secondary>AI analysis</Button></div></Section></>; }

function Markets() { const markets=['BTC/USD','ETH/USD','EUR/USD','Gold','S&P 500']; return <><PageHead eyebrow="SUPPORTED MARKETS" title="Markets" sub="Market information appears only when an authorized provider connection supplies it."/><div className="tabs"><Link className="active" href="/markets">Favorites</Link><Link href="/markets?category=forex">Forex</Link><Link href="/markets?category=synthetic">Synthetic / Supported</Link><Link href="/markets?category=indices">Indices</Link><Link href="/markets?category=commodities">Commodities</Link></div><div className="marketGrid">{markets.map((m,i)=><Link className="market" href={`/market-detail?market=${encodeURIComponent(m)}`} key={m}><div><strong>{m}</strong><small>{i%2?'Forex / Supported':'Provider market'}</small></div><div className="marketPrice">Awaiting live data<small>—</small></div><Badge>LIVE DATA REQUIRED</Badge><ChevronRight size={17}/></Link>)}</div></>; }

function MarketDetail() { const params=useSearchParams(); const market=params.get('market') || 'Selected market'; return <><PageHead eyebrow="MARKET DETAIL" title={market} sub="Live price, chart and provider data will populate after authorized market-data access."/><Card className="chartCard"><div className="chartPlaceholder"><TrendingUp size={28}/><strong>Live chart awaiting provider data</strong><span>No simulated price or performance is displayed.</span></div></Card><div className="analysisGrid"><Card><span className="label">AI ANALYSIS</span><div className="analysisRows"><div><span>Trend</span><b>Awaiting data</b></div><div><span>Momentum</span><b>Awaiting data</b></div><div><span>Volatility</span><b>Awaiting data</b></div><div><span>Market condition</span><b>Awaiting data</b></div></div></Card><Card><span className="label">AI RESULT</span><div className="aiResult">WAIT</div><p className="muted">Confidence: Not available until current market data is supplied.</p><Button href={`/ai-premium?market=${encodeURIComponent(market)}`}>Analyze with AI</Button></Card></div><Section title="Next step" sub="AI analysis is advisory only. Real execution remains user-confirmed and server-controlled."><Button href={`/trade?market=${encodeURIComponent(market)}`}>Open trade / investment flow</Button></Section></>; }

function AIPremium() { const params=useSearchParams(); const market=params.get('market'); return <><PageHead eyebrow="INTELLIGENCE LAYER" title="Orenza AI Premium" sub={market?`Analysis workspace for ${market}. AI recommends; it does not execute.`:'AI analyzes market information and recommends. It does not automatically execute real trades.'} action={<Badge tone="good">ADVISORY ONLY</Badge>}/><Card className="premiumHero"><Sparkles size={26}/><div><strong>Market Scanner</strong><span>Trending opportunities will appear from authorized provider data.</span></div></Card><div className="signalGrid">{['Market scanner','Trend monitor','Momentum monitor'].map(x=><Card key={x}><span className="label">{x.toUpperCase()}</span><h3>Awaiting authorized data</h3><p className="muted">No invented signals, confidence scores or profit claims.</p><Button href={market?`/trade?market=${encodeURIComponent(market)}`:'/markets'} secondary>{market?'Open trade ticket':'View markets'}</Button></Card>)}</div></>; }

function Trade() {
  const router=useRouter(); const params=useSearchParams();
  const [draft,setDraft]=useState<TradeDraft>(()=>({...EMPTY_DRAFT, market:params.get('market') || ''}));
  const [error,setError]=useState('');
  useEffect(()=>{ try { const saved=window.sessionStorage.getItem(DRAFT_KEY); if(saved) setDraft(JSON.parse(saved)); } catch {} },[]);
  const set=(patch:Partial<TradeDraft>)=>setDraft(d=>({...d,...patch}));
  const review=()=>{
    setError('');
    if(!draft.market.trim()) return setError('Choose a market before reviewing.');
    const amount=Number(draft.amount);
    if(!Number.isFinite(amount) || amount<=0) return setError('Enter a valid sandbox amount greater than zero.');
    if(draft.account!=='SANDBOX') return setError('Only SANDBOX is available for this controlled demo flow.');
    try { window.sessionStorage.setItem(DRAFT_KEY,JSON.stringify(draft)); } catch {}
    router.push('/trade/confirm');
  };
  return <><PageHead eyebrow="USER-CONFIRMED ACTION" title="Trade / Investment ticket" sub="Build a sandbox ticket, review it, then explicitly confirm it."/><Card><div className="formGrid">
    <label>Selected account<div className="choiceRow">{['SANDBOX','DERIV','MT5'].map(x=><button type="button" key={x} onClick={()=>set({account:x})} className={draft.account===x?'choice selected':'choice'}>{x}{x!=='SANDBOX'&&<small>{x==='DERIV'?'Connected':'Not connected'}</small>}</button>)}</div></label>
    <label>Selected market<select value={draft.market} onChange={e=>set({market:e.target.value})}><option value="">Choose from Markets</option>{['BTC/USD','ETH/USD','EUR/USD','Gold','S&P 500'].map(m=><option key={m} value={m}>{m}</option>)}</select></label>
    <label>Direction<div className="choiceRow"><button type="button" onClick={()=>set({direction:'BUY'})} className={draft.direction==='BUY'?'choice selected':'choice'}>BUY</button><button type="button" onClick={()=>set({direction:'SELL'})} className={draft.direction==='SELL'?'choice selected':'choice'}>SELL</button></div></label>
    <label>Amount / Volume<input inputMode="decimal" value={draft.amount} onChange={e=>set({amount:e.target.value})} placeholder="$0.00" /></label>
    <label>Stop Loss<input inputMode="decimal" value={draft.stopLoss} onChange={e=>set({stopLoss:e.target.value})} placeholder="Optional" /></label>
    <label>Take Profit<input inputMode="decimal" value={draft.takeProfit} onChange={e=>set({takeProfit:e.target.value})} placeholder="Optional" /></label>
  </div><div className="reviewBox"><strong>SOURCE: {draft.account}</strong><span>MARKET: {draft.market || '—'}</span><span>DIRECTION: {draft.direction}</span><span>AMOUNT: {draft.amount || '—'}</span><span>STATUS: VIRTUAL SANDBOX ACTIVITY</span></div><div className="warning"><ShieldCheck size={18}/><span>AI recommendations never execute automatically. Real provider execution remains disabled in this flow.</span></div>{error&&<div className="warning"><X size={18}/><span>{error}</span></div>}<Button onClick={review}>Review action</Button></Card></>;
}

function Confirm() {
  const router=useRouter(); const [draft,setDraft]=useState<TradeDraft>(EMPTY_DRAFT); const [done,setDone]=useState(false);
  useEffect(()=>{ try { const raw=window.sessionStorage.getItem(DRAFT_KEY); if(raw) setDraft(JSON.parse(raw)); } catch {} },[]);
  const confirm=()=>{ if(!draft.market || !Number(draft.amount)) return; const id=`SBX-${Date.now().toString(36).toUpperCase()}`; try { const current=JSON.parse(window.localStorage.getItem(ACTIVITY_KEY)||'[]'); current.unshift({id,...draft,status:'SETTLED_DEMO',createdAt:new Date().toISOString(),pnl:0}); window.localStorage.setItem(ACTIVITY_KEY,JSON.stringify(current)); window.sessionStorage.removeItem(DRAFT_KEY); } catch {} setDone(true); };
  if(done) return <><PageHead eyebrow="SANDBOX CONFIRMED" title="Action recorded" sub="The demo action was recorded locally as virtual activity; no real order was submitted."/><Card><div className="notice"><CheckCircle2 size={20}/><div><strong>Sandbox action complete</strong><span>Recorded as virtual activity. No Deriv, MT5 or real-money order was sent.</span></div></div><div className="buttonRow"><Button href="/activity">View activity</Button><Button href="/trade" secondary>New trade</Button></div></Card></>;
  return <><PageHead eyebrow="CONFIRMATION" title="Review your action" sub="Nothing is submitted until you explicitly confirm."/><Card><div className="reviewList">{[['Account',draft.account],['Market',draft.market||'Not selected'],['Direction',draft.direction],['Amount',draft.amount?`$${draft.amount}`:'Not selected'],['Risk controls',[draft.stopLoss?`SL ${draft.stopLoss}`:'No stop loss',draft.takeProfit?`TP ${draft.takeProfit}`:'No take profit'].join(' • ') ]].map(([x,v])=><div key={x}><span>{x}</span><strong>{v}</strong></div>)}</div><div className="warning"><ShieldCheck size={18}/><span>DEMO ONLY: confirmation records virtual activity and cannot submit a real-money order.</span></div><div className="buttonRow"><Button href="/trade" secondary>Cancel</Button><Button onClick={confirm}>Confirm sandbox action</Button></div></Card></>;
}

function Portfolio() { return <><PageHead eyebrow="SEPARATED RECORDS" title="Portfolio" sub="Provider and sandbox records are never merged into one balance."/>{['SANDBOX ACTIVITY','DERIV ACTIVITY','MT5 ACTIVITY'].map((x,i)=><Section key={x} title={x} sub={i===0?'Virtual records':'Provider-reported records'}><div className="empty"><FileText size={20}/><span>No records available yet.</span><small>Open / closed / result / history will appear here.</small></div></Section>)}</>; }
function Wallet() { return <><PageHead eyebrow="ACCOUNT OVERVIEW" title="Orenza Wallet" sub="Separate source balances, internal units and genuinely eligible payout funds."/><div className="walletGrid">{[['SANDBOX WALLET','$5,000','30-day virtual welcome capital'],['DERIV ACCOUNT','Connected','Provider-reported information'],['MT5 ACCOUNT','Not Connected','Provider-reported information'],['PROFIT UNITS','0 Units','Internal Orenza calculation'],['PAYOUT ELIGIBILITY','$0','Only genuinely eligible balance']].map(([a,b,c])=><Card key={a}><span className="label">{a}</span><strong className="metricValue">{b}</strong><small>{c}</small></Card>)}</div><Section title="Wallet navigation" sub="Inspect each category without combining its accounting meaning."><div className="quickGrid"><Link className="quick" href="/activity"><Activity size={18}/><span>Transaction history</span><ChevronRight size={16}/></Link><Link className="quick" href="/profit-units"><CircleDollarSign size={18}/><span>Profit Units</span><ChevronRight size={16}/></Link><Link className="quick" href="/payout"><CreditCard size={18}/><span>Payout</span><ChevronRight size={16}/></Link></div></Section></>; }
function ProfitUnits() { return <><PageHead eyebrow="INTERNAL RECORDS" title="Profit Units" sub="Profit Units are internal records and do not automatically represent cash."/><div className="metricGrid"><Metric label="TOTAL UNITS" value="0" sub="No verified records" icon={CircleDollarSign}/><Metric label="UNIT VALUE" value="Not set" sub="Accounting rule required" icon={CreditCard}/></div><Section title="Activity history" sub="Unit ID • Source • Amount • Date • Status"><div className="empty"><FileText size={20}/><span>No Profit Unit records.</span></div></Section></>; }
function Payout() { return <><PageHead eyebrow="CONTROLLED PAYOUT" title="Payout" sub="Real-money transfer remains disabled until approved provider, reconciliation and security requirements are complete."/><Card><div className="heroBalance"><span>Eligible Balance</span><strong>$0.00</strong><small>Only genuinely eligible funds can be requested.</small></div><div className="formGrid"><label>Payout method<select><option>Approved local method</option></select></label><label>Amount<input placeholder="$0.00" /></label></div><div className="warning"><LockKeyhole size={18}/><span>Payout requests are server-controlled. No transfer is initiated by this interface.</span></div><Button href="/payout/security">Request payout</Button></Card><Section title="Payout status flow" sub="Every request receives a unique PAY-XXXXXXXX identifier."><div className="steps">{['Security check','Eligibility check','Duplicate check','Approved local provider','Processing','Ledger record'].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span>{x}</div>)}</div></Section><Section title="History" sub="Review previous requests."><Button href="/payout-history" secondary>Open payout history</Button></Section></>; }
function PayoutSecurity() { return <><PageHead eyebrow="SECURITY CHECK" title="Verify payout access" sub="This is a protected checkpoint before any payout request could be created."/><Card><div className="checkList">{['Session security','Balance eligibility','Duplicate request check','Provider availability'].map(x=><div key={x}><CheckCircle2 size={18}/><span>{x}</span><Badge>CHECK REQUIRED</Badge></div>)}</div><div className="warning"><ShieldCheck size={18}/><span>Payout remains disabled until backend validation and approved provider integration are active.</span></div><Button href="/payout">Return to payout</Button></Card></>; }
function ActivityPage() { const [filter,setFilter]=useState('All'); const [items,setItems]=useState<any[]>([]); useEffect(()=>{try{setItems(JSON.parse(window.localStorage.getItem(ACTIVITY_KEY)||'[]'));}catch{}},[]); const shown=filter==='All'?items:items.filter(x=>x.account===filter); return <><PageHead eyebrow="AUDITABLE HISTORY" title="Activity / Ledger" sub="A complete source-separated history of platform events."/><div className="tabs">{['All','SANDBOX','DERIV','MT5'].map(x=><button type="button" key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div><Card>{shown.length?<div className="reviewList">{shown.map(x=><div key={x.id}><span>{x.id}<small>{new Date(x.createdAt).toLocaleString()}</small></span><strong>{x.direction} {x.market} • ${x.amount} • {x.status}</strong></div>)}</div>:<div className="empty"><Activity size={20}/><span>No {filter==='All'?'':' '+filter.toLowerCase()+' '}activity records yet.</span><small>Unique ID • type • source • amount • status • date</small></div>}</Card></>; }
function PayoutHistory() { return <><PageHead eyebrow="PAYOUT RECORDS" title="Payout History" sub="Every payout request is independently tracked."/><Card><div className="empty"><CreditCard size={20}/><span>No payout records.</span><small>Payout ID • Amount • Method • Date • Status</small></div></Card></>; }
function Security() { return <SecurityActions/>; }
function SecurityActions(){ const [message,setMessage]=useState(''); const act=(name:string)=>setMessage(`${name} is available only through authenticated server-side security controls. No session was changed from this demo interface.`); return <><PageHead eyebrow="PROTECTION" title="Security Center" sub="Review sessions, devices and recent security activity."/><div className="signalGrid"><Card><LockKeyhole size={20}/><h3>Active sessions</h3><p className="muted">Current private session</p><Button href="/settings" secondary>Manage</Button></Card><Card><ShieldCheck size={20}/><h3>Trusted devices</h3><p className="muted">No additional devices shown.</p><Button href="/settings" secondary>Review</Button></Card><Card><Activity size={20}/><h3>Recent security activity</h3><p className="muted">Review the audit ledger.</p><Button href="/activity" secondary>Review activity</Button></Card></div><div className="buttonRow"><button type="button" className="btn secondary" onClick={()=>act('Sign out other devices')}>Sign out other devices <LogOut size={16}/></button><button type="button" className="btn secondary" onClick={()=>act('Revoke session')}>Revoke session <X size={16}/></button></div>{message&&<div className="warning"><ShieldCheck size={18}/><span>{message}</span></div>}</>; }
function SettingsPage() { const sections=[['PROFILE','/settings?section=profile'],['CONNECTED ACCOUNTS','/settings?section=accounts'],['DERIV CONNECTION','/settings?section=deriv'],['MT5 CONNECTION','/settings?section=mt5'],['SECURITY','/security'],['ACTIVE DEVICES','/security?section=devices'],['SESSIONS','/security?section=sessions'],['NOTIFICATIONS','/settings?section=notifications'],['PAYOUT SETTINGS','/settings?section=payout'],['PRIVACY','/settings?section=privacy']]; const params=useSearchParams(); const section=params.get('section'); return <><PageHead eyebrow="CONTROL CENTER" title="Settings" sub="Manage profile, connections, security, notifications, payout settings and privacy."/>{section&&<div className="notice"><Settings size={20}/><div><strong>{section.replace('-', ' ').toUpperCase()}</strong><span>Settings section selected. Changes require authenticated server-side controls.</span></div></div>}<div className="settingsGrid">{sections.map(([x,href])=><Link className="setting" href={href} key={x}><UserRound size={18}/><div><strong>{x}</strong><small>{x==='DERIV CONNECTION'?'Connected':x==='MT5 CONNECTION'?'Not connected':'Manage settings'}</small></div><ChevronRight size={16}/></Link>)}</div></>; }
function Listing({title,icon:Icon,items,base}:{title:string;icon:any;items:string[];base:string}) { return <><PageHead eyebrow="OFFICIAL ORENZA CONTENT" title={title} sub="Content is presented from authorized Orenza sources."/><div className="signalGrid">{items.map((x,i)=><Card key={x}><Icon size={20}/><h3>{x}</h3><p className="muted">Details will appear when published.</p><Button href={`/${base}/${i+1}`} secondary>View</Button></Card>)}</div></>; }
function Content({screen}:{screen:string}) {
  if(screen==='home') return <Dashboard/>; if(screen==='sandbox') return <Sandbox/>; if(screen==='markets') return <Markets/>; if(screen==='market-detail') return <MarketDetail/>;
  if(screen==='ai-premium') return <AIPremium/>; if(screen==='trade') return <Trade/>; if(screen==='trade/confirm') return <Confirm/>; if(screen==='portfolio') return <Portfolio/>;
  if(screen==='wallet') return <Wallet/>; if(screen==='profit-units') return <ProfitUnits/>; if(screen==='payout') return <Payout/>; if(screen==='payout/security') return <PayoutSecurity/>;
  if(screen==='payout-history') return <PayoutHistory/>; if(screen==='activity') return <ActivityPage/>; if(screen==='security') return <Security/>; if(screen==='settings') return <SettingsPage/>;
  if(screen==='announcements') return <Listing title="Announcements" icon={Bell} base="announcements" items={['Private platform update','Security maintenance notice','New market coverage']}/>;
  if(screen==='events') return <Listing title="Events" icon={Clock3} base="events" items={['Upcoming Orenza session','Live market briefing','Past platform event']}/>;
  if(screen==='videos') return <Listing title="Videos" icon={PlayCircle} base="videos" items={['Education','Markets','Platform Updates','Events']}/>;
  if(screen.startsWith('announcements/')||screen.startsWith('events/')||screen.startsWith('videos/')) return <ContentDetail screen={screen}/>;
  return <NotFound/>;
}
function ContentDetail({screen}:{screen:string}) { const [base,id]=screen.split('/'); const title=base==='announcements'?'Announcement':base==='events'?'Event':'Video'; return <><PageHead eyebrow={base.toUpperCase()} title={`${title} ${id}`} sub="This content detail route is now distinct from the listing screen."/><Card><div className="empty"><FileText size={20}/><span>Content detail placeholder</span><small>Authorized content will appear here when published.</small></div><Button href={`/${base}`} secondary>Back to {base}</Button></Card></>; }
function NotFound(){ return <><PageHead eyebrow="NAVIGATION ERROR" title="Screen not found" sub="This route is not part of the Orenza platform navigation."/><Card><div className="warning"><X size={18}/><span>Use the platform navigation to continue.</span></div><Button href="/">Return home</Button></Card></>; }

export default function Platform() {
  const pathname=usePathname(); const [open,setOpen]=useState(false); const screen=pathname.split('/').filter(Boolean).join('/')||'home';
  return <div className="appShell"><aside className={open?'open':''}><div className="brand"><span>O</span><b>ORENZA</b></div><div className="privateTag"><LockKeyhole size={14}/> PRIVATE ACCESS</div><nav>{nav.map(([key,title,Icon])=><Link href={`/${key}`} className={screen===key?'active':''} key={key} onClick={()=>setOpen(false)}><Icon size={17}/><span>{title}</span></Link>)}</nav><div className="sideSecurity"><ShieldCheck size={18}/><div><b>Secure mode</b><small>Credentials stay server-side</small></div></div></aside><main><div className="mobileBar"><button type="button" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><div className="brand"><span>O</span><b>ORENZA</b></div></div><div className="topbar"><span>{labels[screen]||screen.toUpperCase()}</span><div><Badge tone="good">PRIVATE</Badge><Link className="profile" href="/settings?section=profile" aria-label="Open profile"><UserRound size={16}/></Link></div></div><div className="content"><Content screen={screen}/></div></main></div>;
}
