import { NextResponse } from 'next/server';
import crypto from 'node:crypto';
import { createClient } from '@supabase/supabase-js';

function admin() {
  const url = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SECRET_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;
  return url && key ? createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false } }) : null;
}

async function sendCodeEmail(to: string, code: string, fullName?: string, phone?: string) {
  const apiKey = process.env.RESEND_API_KEY;
  const from = process.env.RESEND_FROM_EMAIL;
  if (!apiKey || !from) return false;
  const greeting = fullName ? `Hello ${fullName},` : 'Hello,';
  const phoneLine = phone ? `\nRegistered phone: ${phone}` : '';
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 4500);
  try {
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      signal: controller.signal,
      headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        from,
        to: [to],
        subject: 'Your Orenza identity verification code',
        text: `${greeting}\n\nYour Orenza identity verification code is ${code}.${phoneLine}\n\nIt expires in 10 minutes and can only be used once. Do not share this code. This code is sent by email only; Orenza does not send this verification code to your phone number.`,
      }),
    });
    return response.ok;
  } catch {
    return false;
  } finally {
    clearTimeout(timeout);
  }
}

async function publicAuth() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL;
  const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  return url && key ? createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false } }) : null;
}

export async function POST(req: Request) {
  try {
    const auth = req.headers.get('authorization');
    if (!auth?.startsWith('Bearer ')) return NextResponse.json({ error: 'Authentication required' }, { status: 401 });
    const db = admin();
    if (!db) return NextResponse.json({ error: 'Server authentication is not configured' }, { status: 503 });
    const { data: { user }, error: userError } = await db.auth.getUser(auth.slice(7));
    if (userError || !user?.email) return NextResponse.json({ error: 'A verified email address is required' }, { status: 401 });

    const { data: recent } = await db.from('kyc_face_otp_challenges').select('created_at')
      .eq('user_id', user.id).order('created_at', { ascending: false }).limit(1).maybeSingle();
    if (recent && Date.now() - new Date(recent.created_at).getTime() < 60_000) {
      return NextResponse.json({ error: 'Please wait 60 seconds before requesting another code.' }, { status: 429 });
    }

    await db.from('kyc_face_otp_challenges').update({ consumed_at: new Date().toISOString() })
      .eq('user_id', user.id).is('consumed_at', null);

    // OTPs must be generated by a cryptographically secure server RNG, not by AI or the browser.
    const code = String(crypto.randomInt(100000, 1000000));
    const codeHash = crypto.createHash('sha256').update(code).digest('hex');
    const expiresAt = new Date(Date.now() + 10 * 60_000).toISOString();
    const { data: challenge, error: insertError } = await db.from('kyc_face_otp_challenges').insert({
      user_id: user.id, code_hash: codeHash, expires_at: expiresAt, attempts: 0,
    }).select('id,expires_at').single();
    if (insertError) return NextResponse.json({ error: 'Could not create the verification challenge.' }, { status: 500 });

    const fullName = String(user.user_metadata?.full_name || '');
    const phone = String(user.user_metadata?.phone || '');
    const sent = await sendCodeEmail(user.email, code, fullName, phone);
    if (sent) {
      await db.from('kyc_events').insert({ user_id: user.id, event_type: 'FACE_OTP_ISSUED', metadata: { challenge_id: challenge.id, expires_at: expiresAt, delivery: 'email' } });
      return NextResponse.json({ challenge_id: challenge.id, expires_at: challenge.expires_at, email: user.email, delivery: 'email' });
    }

    // If Orenza's transactional email provider is unavailable, use Supabase Auth email OTP.
    await db.from('kyc_face_otp_challenges').update({ consumed_at: new Date().toISOString() }).eq('id', challenge.id);
    const authClient = await publicAuth();
    if (!authClient) return NextResponse.json({ error: 'Email delivery is temporarily unavailable. Please try again.' }, { status: 503 });
    const { error: otpError } = await authClient.auth.signInWithOtp({ email: user.email, options: { shouldCreateUser: false } });
    if (otpError) return NextResponse.json({ error: `Email OTP could not be sent: ${otpError.message}` }, { status: 503 });
    const fallbackChallenge = `supabase:${encodeURIComponent(user.email)}:face`;
    await db.from('kyc_events').insert({ user_id: user.id, event_type: 'FACE_OTP_ISSUED', metadata: { challenge_id: fallbackChallenge, delivery: 'supabase_email' } });
    return NextResponse.json({ challenge_id: fallbackChallenge, expires_at: new Date(Date.now() + 60 * 60_000).toISOString(), email: user.email, delivery: 'email' });
  } catch {
    return NextResponse.json({ error: 'Unable to send the identity verification code by email.' }, { status: 500 });
  }
}
