alter table public.broker_connections add column if not exists access_token_encrypted text;
alter table public.broker_connections add column if not exists refresh_token_encrypted text;
alter table public.broker_connections add column if not exists token_expires_at timestamptz;
alter table public.broker_connections add column if not exists last_connected_at timestamptz;
alter table public.broker_connections add column if not exists last_heartbeat_at timestamptz;
alter table public.broker_connections add column if not exists last_error text;
create index if not exists broker_connections_health_idx on public.broker_connections(status, last_heartbeat_at);
create table if not exists public.broker_account_snapshots (id uuid primary key default gen_random_uuid(), connection_id uuid not null references public.broker_connections(id) on delete cascade, broker text not null check (broker in ('DERIV','MT5')), environment text not null check (environment in ('DEMO','REAL')), external_account_id text not null, currency text, balance numeric, equity numeric, available numeric, margin numeric, profit numeric, as_of timestamptz not null default now(), source text not null, raw jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index if not exists broker_account_snapshots_connection_idx on public.broker_account_snapshots(connection_id, as_of desc);
create table if not exists public.broker_positions (id uuid primary key default gen_random_uuid(), connection_id uuid not null references public.broker_connections(id) on delete cascade, broker text not null check (broker in ('DERIV','MT5')), environment text not null check (environment in ('DEMO','REAL')), external_account_id text not null, external_position_id text not null, symbol text not null, side text, quantity numeric, entry_price numeric, current_price numeric, profit numeric, as_of timestamptz not null default now(), raw jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index if not exists broker_positions_connection_idx on public.broker_positions(connection_id, as_of desc);
create table if not exists public.broker_events (id uuid primary key default gen_random_uuid(), connection_id uuid not null references public.broker_connections(id) on delete cascade, broker text not null check (broker in ('DERIV','MT5')), environment text not null check (environment in ('DEMO','REAL')), event_type text not null, external_event_id text, occurred_at timestamptz not null default now(), payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), unique(connection_id, event_type, external_event_id));
create index if not exists broker_events_connection_idx on public.broker_events(connection_id, occurred_at desc);
create table if not exists public.reconciliation_runs (id uuid primary key default gen_random_uuid(), connection_id uuid not null references public.broker_connections(id) on delete cascade, status text not null check (status in ('MATCHED','MISMATCH','ERROR')), broker_balance numeric, ledger_balance numeric, delta numeric, broker_positions_count integer, ledger_positions_count integer, details jsonb not null default '{}'::jsonb, started_at timestamptz not null default now(), completed_at timestamptz);
create index if not exists reconciliation_runs_connection_idx on public.reconciliation_runs(connection_id, started_at desc);
alter table public.broker_connections enable row level security;
alter table public.broker_account_snapshots enable row level security;
alter table public.broker_positions enable row level security;
alter table public.broker_events enable row level security;
alter table public.reconciliation_runs enable row level security;
drop policy if exists broker_connections_owner_select on public.broker_connections;
drop policy if exists broker_connections_owner_insert on public.broker_connections;
drop policy if exists broker_connections_owner_update on public.broker_connections;
drop policy if exists broker_snapshots_owner_select on public.broker_account_snapshots;
drop policy if exists broker_positions_owner_select on public.broker_positions;
drop policy if exists broker_events_owner_select on public.broker_events;
drop policy if exists reconciliation_owner_select on public.reconciliation_runs;
create policy broker_connections_owner_select on public.broker_connections for select to authenticated using ((select auth.uid()) = user_id);
create policy broker_connections_owner_insert on public.broker_connections for insert to authenticated with check ((select auth.uid()) = user_id);
create policy broker_connections_owner_update on public.broker_connections for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy broker_snapshots_owner_select on public.broker_account_snapshots for select to authenticated using (exists (select 1 from public.broker_connections c where c.id = connection_id and c.user_id = (select auth.uid())));
create policy broker_positions_owner_select on public.broker_positions for select to authenticated using (exists (select 1 from public.broker_connections c where c.id = connection_id and c.user_id = (select auth.uid())));
create policy broker_events_owner_select on public.broker_events for select to authenticated using (exists (select 1 from public.broker_connections c where c.id = connection_id and c.user_id = (select auth.uid())));
create policy reconciliation_owner_select on public.reconciliation_runs for select to authenticated using (exists (select 1 from public.broker_connections c where c.id = connection_id and c.user_id = (select auth.uid())));
