-- Sandbox financial RPCs must execute only for the authenticated caller.
-- SECURITY DEFINER is required because the RPCs atomically write ledger rows protected by RLS.
create or replace function public.request_sandbox_allocation(p_amount numeric, p_idempotency_key text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v_user uuid:=auth.uid(); v_wallet public.sandbox_wallets%rowtype; v_today date:=current_date; v_ref text:='SAN-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,12)); v_alloc public.sandbox_allocations%rowtype; begin if v_user is null then raise exception 'AUTH_REQUIRED'; end if; if p_amount<50 or p_amount>200 then raise exception 'SANDBOX_ALLOCATION_LIMIT'; end if; if p_idempotency_key is null or length(trim(p_idempotency_key))<8 then raise exception 'INVALID_IDEMPOTENCY_KEY'; end if; select * into v_wallet from public.sandbox_wallets where user_id=v_user and currency='USD' for update; if not found then insert into public.sandbox_wallets(user_id,currency,balance,allocated,available_balance,reserved_balance,lifetime_allocated,daily_allocated,daily_allocation_date) values(v_user,'USD',0,0,0,0,0,0,v_today) returning * into v_wallet; end if; if v_wallet.daily_allocation_date is distinct from v_today then update public.sandbox_wallets set daily_allocated=0,daily_allocation_date=v_today,updated_at=now() where id=v_wallet.id; v_wallet.daily_allocated:=0; end if; if v_wallet.daily_allocated+p_amount>200 then raise exception 'DAILY_SANDBOX_LIMIT'; end if; select * into v_alloc from public.sandbox_allocations where idempotency_key=p_idempotency_key and user_id=v_user; if found then return jsonb_build_object('reference_id',v_alloc.reference_id,'allocation_id',v_alloc.id,'status',v_alloc.status); end if; insert into public.sandbox_allocations(user_id,amount,status,approved_at,allocated_at,reference_id,idempotency_key) values(v_user,p_amount,'ALLOCATED',now(),now(),v_ref,p_idempotency_key) returning * into v_alloc; update public.sandbox_wallets set balance=balance+p_amount,allocated=allocated+p_amount,available_balance=available_balance+p_amount,lifetime_allocated=lifetime_allocated+p_amount,daily_allocated=daily_allocated+p_amount,daily_allocation_date=v_today,updated_at=now() where id=v_wallet.id; insert into public.sandbox_ledger_entries(user_id,wallet_id,allocation_id,entry_type,direction,amount,reference_id,metadata) values(v_user,v_wallet.id,v_alloc.id,'ALLOCATION','CREDIT',p_amount,'LED-'||v_ref,jsonb_build_object('mode','SANDBOX','virtual',true)); return jsonb_build_object('reference_id',v_alloc.reference_id,'allocation_id',v_alloc.id,'status',v_alloc.status,'amount',p_amount); end; $$;

create or replace function public.create_sandbox_order(p_symbol text,p_side text,p_quantity numeric,p_entry_price numeric,p_notional_usd numeric,p_stop_loss numeric default null,p_take_profit numeric default null,p_idempotency_key text default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v_user uuid:=auth.uid(); v_wallet public.sandbox_wallets%rowtype; v_order public.sandbox_orders%rowtype; v_ref text:='SORD-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,12)); begin if v_user is null then raise exception 'AUTH_REQUIRED'; end if; if upper(p_side) not in('BUY','SELL') then raise exception 'INVALID_SIDE'; end if; if p_quantity<=0 or p_entry_price<0 or p_notional_usd<=0 or p_notional_usd>200 then raise exception 'INVALID_ORDER'; end if; if p_idempotency_key is null or length(trim(p_idempotency_key))<8 then raise exception 'INVALID_IDEMPOTENCY_KEY'; end if; select * into v_order from public.sandbox_orders where idempotency_key=p_idempotency_key and user_id=v_user; if found then return jsonb_build_object('order_id',v_order.id,'reference_id',v_order.reference_id,'status',v_order.status); end if; select * into v_wallet from public.sandbox_wallets where user_id=v_user and currency='USD' for update; if not found then raise exception 'SANDBOX_WALLET_NOT_FOUND'; end if; if v_wallet.available_balance<p_notional_usd then raise exception 'INSUFFICIENT_SANDBOX_BALANCE'; end if; insert into public.sandbox_orders(user_id,symbol,side,quantity,entry_price,stop_loss,take_profit,notional_usd,status,reference_id,idempotency_key,metadata) values(v_user,p_symbol,upper(p_side),p_quantity,p_entry_price,p_stop_loss,p_take_profit,p_notional_usd,'EXECUTED',v_ref,p_idempotency_key,jsonb_build_object('mode','SANDBOX','simulation',true)) returning * into v_order; update public.sandbox_wallets set available_balance=available_balance-p_notional_usd,reserved_balance=reserved_balance+p_notional_usd,updated_at=now() where id=v_wallet.id; insert into public.sandbox_ledger_entries(user_id,wallet_id,order_id,entry_type,direction,amount,reference_id,metadata) values(v_user,v_wallet.id,v_order.id,'RESERVE','DEBIT',p_notional_usd,'LED-'||v_ref,jsonb_build_object('mode','SANDBOX','symbol',p_symbol,'side',upper(p_side))); return jsonb_build_object('order_id',v_order.id,'reference_id',v_order.reference_id,'status',v_order.status,'reserved_usd',p_notional_usd); end; $$;

create or replace function public.orenza_initialize_sandbox(p_user_id uuid) returns public.orenza_balance_snapshots language plpgsql security definer set search_path=public,pg_temp as $$ declare v_snapshot public.orenza_balance_snapshots; begin if auth.uid() is null or p_user_id is null or auth.uid()<>p_user_id then raise exception 'UNAUTHORIZED'; end if; insert into public.sandbox_wallets(user_id,currency,balance,allocated,available_balance,reserved_balance) values(p_user_id,'USD',0,0,0,0) on conflict(user_id,currency) do nothing; insert into public.orenza_profit_accounts(user_id) values(p_user_id) on conflict do nothing; insert into public.orenza_balance_snapshots(user_id) values(p_user_id); select * into v_snapshot from public.orenza_balance_snapshots where user_id=p_user_id order by captured_at desc limit 1; return v_snapshot; end; $$;

create or replace function public.orenza_record_profit_event(p_user_id uuid,p_amount numeric,p_event_type text,p_trading_result_id uuid default null) returns public.orenza_profit_accounts language plpgsql security definer set search_path=public,pg_temp as $$ declare v_account public.orenza_profit_accounts; v_units numeric; begin if auth.uid() is null or p_user_id is null or auth.uid()<>p_user_id then raise exception 'UNAUTHORIZED'; end if; if p_amount<=0 then raise exception 'amount must be positive'; end if; if p_event_type not in('PROFIT','LOSS','REVERSAL','ADJUSTMENT') then raise exception 'invalid profit event type'; end if; insert into public.orenza_profit_accounts(user_id) values(p_user_id) on conflict(user_id) do nothing; select * into v_account from public.orenza_profit_accounts where user_id=p_user_id for update; v_units:=p_amount/v_account.unit_rate; if p_event_type='PROFIT' then update public.orenza_profit_accounts set gross_profit_units=gross_profit_units+v_units,net_profit_units=net_profit_units+v_units,available_units=available_units+v_units,updated_at=now() where user_id=p_user_id; elsif p_event_type='LOSS' then update public.orenza_profit_accounts set loss_units=loss_units+v_units,updated_at=now() where user_id=p_user_id; else update public.orenza_profit_accounts set updated_at=now() where user_id=p_user_id; end if; insert into public.orenza_profit_events(user_id,trading_result_id,event_type,amount,units,unit_rate,eligible_for_payout) values(p_user_id,p_trading_result_id,p_event_type,p_amount,v_units,false); select * into v_account from public.orenza_profit_accounts where user_id=p_user_id; return v_account; end; $$;

create or replace function public.simulate_sandbox_settlement(p_order_id uuid,p_pnl_usd numeric) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v_user uuid:=auth.uid(); v_order public.sandbox_orders%rowtype; v_wallet public.sandbox_wallets%rowtype; v_ref text; v_return numeric; v_entry_type text; v_amount numeric; begin if v_user is null then raise exception 'AUTH_REQUIRED'; end if; select * into v_order from public.sandbox_orders where id=p_order_id and user_id=v_user for update; if not found then raise exception 'ORDER_NOT_FOUND'; end if; if v_order.status='SETTLED' then return jsonb_build_object('order_id',v_order.id,'status','SETTLED','pnl_usd',v_order.simulated_pnl_usd); end if; if v_order.status<>'EXECUTED' then raise exception 'ORDER_NOT_SETTLEABLE'; end if; if p_pnl_usd<(-1*v_order.notional_usd) then raise exception 'LOSS_EXCEEDS_RESERVED_CAPITAL'; end if; select * into v_wallet from public.sandbox_wallets where user_id=v_user and currency='USD' for update; if not found then raise exception 'SANDBOX_WALLET_NOT_FOUND'; end if; v_return:=greatest(v_order.notional_usd+p_pnl_usd,0); v_entry_type:=case when p_pnl_usd>=0 then 'PROFIT' else 'LOSS' end; v_amount:=abs(p_pnl_usd); v_ref:='SET-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,12)); update public.sandbox_wallets set reserved_balance=reserved_balance-v_order.notional_usd,available_balance=available_balance+v_return,balance=balance+p_pnl_usd,realized_profit=realized_profit+greatest(p_pnl_usd,0),withdrawable_profit=withdrawable_profit+greatest(p_pnl_usd,0),lifetime_profit=lifetime_profit+greatest(p_pnl_usd,0),lifetime_loss=lifetime_loss+greatest(-p_pnl_usd,0),updated_at=now() where id=v_wallet.id; update public.sandbox_orders set status='SETTLED',simulated_pnl_usd=p_pnl_usd,settled_at=now(),updated_at=now() where id=v_order.id; insert into public.sandbox_ledger_entries(user_id,wallet_id,order_id,entry_type,direction,amount,reference_id,metadata) values(v_user,v_wallet.id,v_order.id,'TRADE_SETTLEMENT','CREDIT',v_return,v_ref,jsonb_build_object('mode','SANDBOX','pnl_usd',p_pnl_usd)); if v_amount>0 then insert into public.sandbox_ledger_entries(user_id,wallet_id,order_id,entry_type,direction,amount,reference_id,metadata) values(v_user,v_wallet.id,v_order.id,v_entry_type,case when p_pnl_usd>0 then 'CREDIT' else 'DEBIT' end,v_amount,v_ref||'-PNL',jsonb_build_object('mode','SANDBOX','pnl_usd',p_pnl_usd)); end if; return jsonb_build_object('order_id',v_order.id,'status','SETTLED','pnl_usd',p_pnl_usd,'returned_capital',v_return); end; $$;

create or replace function public.orenza_issue_sandbox_welcome_bonus(p_user_id uuid,p_amount numeric default 5000,p_currency text default 'USD',p_idempotency_key text default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v_wallet public.sandbox_wallets%rowtype; v_bonus public.orenza_sandbox_welcome_bonuses%rowtype; v_ref text; v_key text; v_kyc_status text; begin if auth.uid() is null or p_user_id is null or auth.uid()<>p_user_id then raise exception 'UNAUTHORIZED'; end if; perform public.orenza_assert_sandbox_only_runtime(); if p_amount<>5000 then raise exception 'WELCOME_BONUS_AMOUNT_MUST_BE_5000'; end if; select status::text into v_kyc_status from public.kyc_profiles where user_id=p_user_id limit 1; if coalesce(v_kyc_status,'NOT_STARTED')<>'VERIFIED' then raise exception 'KYC_REQUIRED_BEFORE_SANDBOX_PROMO'; end if; v_key:=coalesce(p_idempotency_key,'welcome:'||p_user_id::text); select * into v_bonus from public.orenza_sandbox_welcome_bonuses where user_id=p_user_id and status in('ACTIVE','CONSUMED') limit 1; if found then return jsonb_build_object('ok',true,'already_issued',true,'bonus',to_jsonb(v_bonus)); end if; v_ref:='ORENZA-WELCOME-5000-'||replace(p_user_id::text,'-',''); insert into public.sandbox_wallets(user_id,currency,balance,allocated,available_balance,reserved_balance,lifetime_allocated,daily_allocated,daily_allocation_date,realized_profit,withdrawable_profit,withdrawn_profit,lifetime_profit,lifetime_loss,payout_reserved_profit) values(p_user_id,upper(trim(p_currency)),0,0,0,0,0,0,current_date,0,0,0,0,0,0) on conflict(user_id,currency) do nothing; select * into v_wallet from public.sandbox_wallets where user_id=p_user_id and currency=upper(trim(p_currency)) for update; insert into public.orenza_sandbox_welcome_bonuses(user_id,amount,currency,expires_at,reference_id,idempotency_key,metadata) values(p_user_id,p_amount,upper(trim(p_currency)),now()+interval '30 days',v_ref,v_key,jsonb_build_object('source','WELCOME_BONUS','virtual_only',true,'no_cash_value',true,'kyc_verified_required',true)) returning * into v_bonus; update public.sandbox_wallets set balance=balance+p_amount,available_balance=available_balance+p_amount,lifetime_allocated=lifetime_allocated+p_amount,daily_allocated=daily_allocated+p_amount,daily_allocation_date=current_date,updated_at=now() where id=v_wallet.id; insert into public.sandbox_allocations(user_id,amount,status,approved_at,allocated_at,metadata,reference_id,idempotency_key) values(p_user_id,p_amount,'ALLOCATED',now(),now(),jsonb_build_object('source','WELCOME_BONUS','expires_at',v_bonus.expires_at,'virtual_only',true),v_ref,v_key) on conflict(idempotency_key) do nothing; return jsonb_build_object('ok',true,'already_issued',false,'bonus',to_jsonb(v_bonus),'wallet_id',v_wallet.id); end; $$;

revoke all on function public.request_sandbox_allocation(numeric,text) from public,anon; grant execute on function public.request_sandbox_allocation(numeric,text) to authenticated;
revoke all on function public.create_sandbox_order(text,text,numeric,numeric,numeric,numeric,numeric,text) from public,anon; grant execute on function public.create_sandbox_order(text,text,numeric,numeric,numeric,numeric,numeric,text) to authenticated;
revoke all on function public.orenza_initialize_sandbox(uuid) from public,anon; grant execute on function public.orenza_initialize_sandbox(uuid) to authenticated;
revoke all on function public.orenza_record_profit_event(uuid,numeric,text,uuid) from public,anon; grant execute on function public.orenza_record_profit_event(uuid,numeric,text,uuid) to authenticated;
revoke all on function public.simulate_sandbox_settlement(uuid,numeric) from public,anon; grant execute on function public.simulate_sandbox_settlement(uuid,numeric) to authenticated;
revoke all on function public.orenza_issue_sandbox_welcome_bonus(uuid,numeric,text,text) from public,anon; grant execute on function public.orenza_issue_sandbox_welcome_bonus(uuid,numeric,text,text) to authenticated;

alter table public.orenza_sandbox_welcome_bonuses enable row level security;
drop policy if exists orenza_welcome_bonus_select_own on public.orenza_sandbox_welcome_bonuses;
create policy orenza_welcome_bonus_select_own on public.orenza_sandbox_welcome_bonuses for select to authenticated using(auth.uid()=user_id);
revoke all on table public.orenza_sandbox_welcome_bonuses from anon,authenticated;
grant select on table public.orenza_sandbox_welcome_bonuses to authenticated;

revoke all on table public.kyc_face_otp_challenges from anon,authenticated;
revoke all on table public.orenza_tester_invites from anon,authenticated;
revoke insert,update,delete on table public.orenza_tester_access from anon,authenticated;
revoke insert,update,delete on table public.orenza_payout_requests from anon,authenticated;
revoke insert,update,delete on table public.orenza_approval_audit from anon,authenticated;
